# Generated by Django 4.1.1 on 2023-12-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.TextField()),
                ("amountOther", models.TextField(null=True)),
                ("payment", models.TextField()),
            ],
        ),
    ]
